In [1]:
#Mean of the absolute erros is called cost function
#Individual errors are called loss
#epochs = 5 means we went through all samples 5 times
#types of errors Mean Absolute error(MAE), Mean Squared Error(MSE)
#Log loss or binary cross entropy we use this for logisticRegression

In [2]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


np.float64(0.5)

In [5]:
#using numpy
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [8]:
mae_np(y_predicted, y_true)

np.float64(0.5)

In [11]:
#Implement Log Loss or Binary Cross Entropy
np.log([0])

C:\Users\Admin\AppData\Local\Temp\ipykernel_15640\682310346.py:2: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [12]:
epsilon = 1e-15

In [13]:
np.log([1e-15])

array([-34.53877639])

In [14]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [15]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [16]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [17]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [18]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [19]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)

In [24]:
def msee(y_true, y_predicted):
    y_error = 0
    for yt, yp in zip(y_true, y_predicted):
        y_error += (yt - yp)**2
    return y_error/len(y_true)
    

In [25]:
msee(y_true, y_predicted)

np.float64(0.366)

In [27]:
np.mean(np.square(y_true-y_predicted))

np.float64(0.366)